auto: true
server: true
encoding: utf-8
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - .bundle
